#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "examples" / "proof_resources.json"
DEFAULT_DEST = REPO_ROOT / "external" / "proof-resources"


def _load_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _slug_from_url(url: str) -> str:
    return url.rstrip("/").split("/")[-1].removesuffix(".git")


def _clone_url(resource: dict[str, Any]) -> str | None:
    if resource.get("type") != "github_repo":
        return None
    url = str(resource.get("url", "")).strip()
    if not url.startswith("https://github.com/"):
        return None
    return f"{url}.git"


def _selected_resources(
    manifest: dict[str, Any],
    *,
    claim: str | None,
    priority: str | None,
    github_only: bool,
) -> list[dict[str, Any]]:
    resources = manifest["resources"]
    selected: list[dict[str, Any]] = []
    for resource in resources:
        if claim is not None and resource.get("claim") != claim:
            continue
        if priority is not None and resource.get("priority") != priority:
            continue
        if github_only and resource.get("type") != "github_repo":
            continue
        selected.append(resource)
    return selected


def _write_index(destination: Path, resources: list[dict[str, Any]]) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    index_json = destination / "selected-resources.json"
    index_md = destination / "README.md"
    index_json.write_text(json.dumps({"resources": resources}, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Materialized Proof Resources",
        "",
        "This directory was generated by `scripts/materialize_proof_resources.py`.",
        "",
        "| ID | Type | Claim | Priority | URL |",
        "| --- | --- | --- | --- | --- |",
    ]
    for resource in resources:
        lines.append(
            f"| `{resource['id']}` | `{resource['type']}` | `{resource['claim']}` | `{resource['priority']}` | {resource['url']} |"
        )
    index_md.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _materialize_repo(resource: dict[str, Any], destination: Path, dry_run: bool) -> str:
    clone_url = _clone_url(resource)
    if clone_url is None:
        return f"skip {resource['id']}: not a GitHub repository resource"

    target = destination / "repos" / f"{resource['id']}-{_slug_from_url(clone_url)}"
    if target.exists() and (target / ".git").exists():
        return f"skip {resource['id']}: already present at {target}"
    if target.exists():
        shutil.rmtree(target)

    command = [
        "git",
        "clone",
        "--depth=1",
        "--filter=blob:none",
        clone_url,
        str(target),
    ]
    if dry_run:
        return f"dry-run {resource['id']}: {' '.join(command)}"

    target.parent.mkdir(parents=True, exist_ok=True)
    env = {**os.environ, "GIT_LFS_SKIP_SMUDGE": "1"}
    try:
        subprocess.run(command, check=True, text=True, env=env, capture_output=True)
        return f"cloned {resource['id']} -> {target}"
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip().splitlines()
        detail = stderr[-1] if stderr else f"exit status {exc.returncode}"
        return f"failed {resource['id']}: {detail}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Materialize external proof resources for AgenVantage claim work."
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    parser.add_argument("--claim", help="Optional claim id to filter resources.")
    parser.add_argument("--priority", help="Optional priority filter such as P0 or P1.")
    parser.add_argument(
        "--github-only",
        action="store_true",
        help="Only include GitHub repository resources.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the clone plan without fetching repositories.",
    )
    args = parser.parse_args()

    manifest = _load_manifest(args.manifest)
    resources = _selected_resources(
        manifest,
        claim=args.claim,
        priority=args.priority,
        github_only=args.github_only,
    )
    _write_index(args.dest, resources)

    print(f"Selected {len(resources)} resources")
    print(f"Index written to {args.dest / 'selected-resources.json'}")

    github_resources = [resource for resource in resources if resource.get("type") == "github_repo"]
    if not github_resources:
        print("No GitHub repositories selected for materialization.")
        return

    print("")
    print("Repository materialization:")
    for resource in github_resources:
        print(_materialize_repo(resource, args.dest, args.dry_run))


if __name__ == "__main__":
    main()
