name: IYKYK Questionnaire

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  models: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  iykyk:
    uses: nicholas-tayag/IYKYK/.github/workflows/reusable-iykyk.yml@v1
